package:
  name: cat_analysis
  version: {{ environ.get("GIT_DESCRIBE_TAG", "0.0.1") }}

source:
  path: .

build:
  number: {{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}
  script:
    - $PYTHON setup.py install
  entry_points:
    - data_preproc      = cli.data_preproc:main
    - temporal_analysis = cli.temporal_analysis:main
    - spatial_analysis = cli.spatial_analysis:main
    - feature_analysis = cli.feature_analysis:main

requirements:
  build:
    - python {{ python }}
    - setuptools
  run:
    - pyyaml
    - numpy
    - pandas
    - xgboost
    - scikit-learn
    - dask
    - basemap
    - basemap-data-hires
    - shap