
region:
  - Auckland
  - Waikato
  - Canterbury
  - Northland
  - Bay of Plenty
  - Manawatū-Whanganui
  - Otago
  - Wellington
  - Hawke's Bay
  - Southland
  - West Coast
  - Nelson
  - Taranaki
  - Tasman
  - Gisborne
  - Marlborough

year:
  - 2018

analysis_fields: # analysis field and constrains
  field1:
    motorcycle: null
  field2:
    bicycle: null
  field3:
    truck: null

vis_scatter_factor: 1.2

use_population_data: null
latlon_data: etc/region_latlon.csv