
region:
  - Auckland
  - Waikato
  - Canterbury
  - Northland
  - Bay of Plenty
  - Manawatū-Whanganui
  - Otago
  - Wellington
  - Hawke's Bay
  - Southland
  - West Coast
  - Nelson
  - Taranaki
  - Tasman
  - Gisborne
  - Marlborough

year:
  - 2005
  - 2006
  - 2007
  - 2008
  - 2009
  - 2010
  - 2011
  - 2012
  - 2013
  - 2014
  - 2015
  - 2016
  - 2017
  - 2018
  - 2019
  - 2020
  - 2021

analysis_fields: # analysis field and constrains
  field1:
    suv:
      speedLimit: 100
  fiel2:
    suv: null