
region:
  - Auckland
  - Waikato
  - Canterbury
  - Northland
  - Bay of Plenty
  - Manawatū-Whanganui
  - Otago
  - Wellington
  - Hawke's Bay
  - Southland
  - West Coast
  - Nelson
  - Taranaki
  - Tasman
  - Gisborne
  - Marlborough

year:
  - 2000
  - 2001
  - 2002
  - 2003
  - 2004
  - 2005
  - 2006
  - 2007
  - 2008
  - 2009
  - 2010
  - 2011
  - 2012
  - 2013
  - 2014
  - 2015
  - 2016
  - 2017
  - 2018
  - 2019
  - 2020
  - 2021

analysis_fields: # analysis field and constrains
  field1:
    bicycle:
      speedLimit: 100
  field2:
    bicycle: null
  field3:
    suv:
      speedLimit: 100
  field4:
    suv: null
  field5:
    truck:
      speedLimit: 100
  field6:
    truck: null
  field7:
    motorcycle:
      speedLimit: 100
  field8:
    motorcycle: null